//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TRQuoteCore.com.omexsystems {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MSDsvcSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class MSDsvc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDiffInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MSDsvc() {
            this.Url = global::TRQuoteCore.Properties.Settings.Default.TRQuoteCore_com_omexsystems_MSDsvc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event getInfoCompletedEventHandler getInfoCompleted;
        
        /// <remarks/>
        public event getDiffInfoCompletedEventHandler getDiffInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MSD getInfo(string symbol, string LoginID, string UserName, string Password) {
            object[] results = this.Invoke("getInfo", new object[] {
                        symbol,
                        LoginID,
                        UserName,
                        Password});
            return ((MSD)(results[0]));
        }
        
        /// <remarks/>
        public void getInfoAsync(string symbol, string LoginID, string UserName, string Password) {
            this.getInfoAsync(symbol, LoginID, UserName, Password, null);
        }
        
        /// <remarks/>
        public void getInfoAsync(string symbol, string LoginID, string UserName, string Password, object userState) {
            if ((this.getInfoOperationCompleted == null)) {
                this.getInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInfoOperationCompleted);
            }
            this.InvokeAsync("getInfo", new object[] {
                        symbol,
                        LoginID,
                        UserName,
                        Password}, this.getInfoOperationCompleted, userState);
        }
        
        private void OngetInfoOperationCompleted(object arg) {
            if ((this.getInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInfoCompleted(this, new getInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDiffInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] getDiffInfo(string Value_TextBox, string Column_Name_Simple, string Column_Name_ddl, string Value_ddl, string LoginID, string UserName, string Password, string Server) {
            object[] results = this.Invoke("getDiffInfo", new object[] {
                        Value_TextBox,
                        Column_Name_Simple,
                        Column_Name_ddl,
                        Value_ddl,
                        LoginID,
                        UserName,
                        Password,
                        Server});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getDiffInfoAsync(string Value_TextBox, string Column_Name_Simple, string Column_Name_ddl, string Value_ddl, string LoginID, string UserName, string Password, string Server) {
            this.getDiffInfoAsync(Value_TextBox, Column_Name_Simple, Column_Name_ddl, Value_ddl, LoginID, UserName, Password, Server, null);
        }
        
        /// <remarks/>
        public void getDiffInfoAsync(string Value_TextBox, string Column_Name_Simple, string Column_Name_ddl, string Value_ddl, string LoginID, string UserName, string Password, string Server, object userState) {
            if ((this.getDiffInfoOperationCompleted == null)) {
                this.getDiffInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDiffInfoOperationCompleted);
            }
            this.InvokeAsync("getDiffInfo", new object[] {
                        Value_TextBox,
                        Column_Name_Simple,
                        Column_Name_ddl,
                        Value_ddl,
                        LoginID,
                        UserName,
                        Password,
                        Server}, this.getDiffInfoOperationCompleted, userState);
        }
        
        private void OngetDiffInfoOperationCompleted(object arg) {
            if ((this.getDiffInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDiffInfoCompleted(this, new getDiffInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MSD {
        
        private string msd_tickerField;
        
        private string msd_nameField;
        
        private string msd_countryField;
        
        private string msd_id_sedol1Field;
        
        private string msd_id_isinField;
        
        private string msd_id_cusipField;
        
        private string msd_security_typField;
        
        private string msd_eqy_prim_exchField;
        
        private string msd_crncyField;
        
        private string msd_to_activField;
        
        private string msd_to_trField;
        
        private string msd_ticker_and_exch_codeField;
        
        private string msd_eqy_prim_exch_shrtField;
        
        /// <remarks/>
        public string msd_ticker {
            get {
                return this.msd_tickerField;
            }
            set {
                this.msd_tickerField = value;
            }
        }
        
        /// <remarks/>
        public string msd_name {
            get {
                return this.msd_nameField;
            }
            set {
                this.msd_nameField = value;
            }
        }
        
        /// <remarks/>
        public string msd_country {
            get {
                return this.msd_countryField;
            }
            set {
                this.msd_countryField = value;
            }
        }
        
        /// <remarks/>
        public string msd_id_sedol1 {
            get {
                return this.msd_id_sedol1Field;
            }
            set {
                this.msd_id_sedol1Field = value;
            }
        }
        
        /// <remarks/>
        public string msd_id_isin {
            get {
                return this.msd_id_isinField;
            }
            set {
                this.msd_id_isinField = value;
            }
        }
        
        /// <remarks/>
        public string msd_id_cusip {
            get {
                return this.msd_id_cusipField;
            }
            set {
                this.msd_id_cusipField = value;
            }
        }
        
        /// <remarks/>
        public string msd_security_typ {
            get {
                return this.msd_security_typField;
            }
            set {
                this.msd_security_typField = value;
            }
        }
        
        /// <remarks/>
        public string msd_eqy_prim_exch {
            get {
                return this.msd_eqy_prim_exchField;
            }
            set {
                this.msd_eqy_prim_exchField = value;
            }
        }
        
        /// <remarks/>
        public string msd_crncy {
            get {
                return this.msd_crncyField;
            }
            set {
                this.msd_crncyField = value;
            }
        }
        
        /// <remarks/>
        public string msd_to_activ {
            get {
                return this.msd_to_activField;
            }
            set {
                this.msd_to_activField = value;
            }
        }
        
        /// <remarks/>
        public string msd_to_tr {
            get {
                return this.msd_to_trField;
            }
            set {
                this.msd_to_trField = value;
            }
        }
        
        /// <remarks/>
        public string msd_ticker_and_exch_code {
            get {
                return this.msd_ticker_and_exch_codeField;
            }
            set {
                this.msd_ticker_and_exch_codeField = value;
            }
        }
        
        /// <remarks/>
        public string msd_eqy_prim_exch_shrt {
            get {
                return this.msd_eqy_prim_exch_shrtField;
            }
            set {
                this.msd_eqy_prim_exch_shrtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getInfoCompletedEventHandler(object sender, getInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MSD Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MSD)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getDiffInfoCompletedEventHandler(object sender, getDiffInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDiffInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDiffInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591